#pragma once

#define RPL_WELCOME(Nick) "ircserv: Welcome to the ircserv, " + Nick + ". (001)"
#define ERR_NOTREGISTERED() "ircserv :You have not registered. (451)"
#define ERR_CUSTOM(Message) "ircserv Error: " + Message
#define ERR_NOSUCHNICK(Nickname) "ircserv " + Nickname + ": No such nick. (401)"
#define ERR_NOSUCHCHANNEL(Channel) "ircserv " + Channel + " :No such channel. (403)"
#define ERR_CANNOTSENDTOCHAN(Channel) "ircserv " + Channel + ":Cannot send to channel. (404)"
#define ERR_TOOMANYCHANNELS(Channel) "ircserv " + Channel + " :You have joined too many channels. (405)"
#define ERR_NORECIPIENT(Command) "ircserv :No recipient given for " + Command + " (411)"
#define ERR_NOTEXTTOSEND() "ircserv :No text to send. (412)"
#define ERR_INPUTTOOLONG() "ircserv :Input line was too long. (417)"
#define ERR_UNKNOWNCOMMAND(Command) "ircserv " + Command + " :Unknown command. (421)"
#define ERR_NONICKNAMEGIVEN() "ircserv :No nickname given. (431)"
#define ERR_ERRONEUSNICKNAME(Nick) "ircserv " + Nick + " :Erroneus nickname. (432)"
#define ERR_NICKNAMEINUSE(Nick) "ircserv " + Nick + " :Nickname is already in use. (433)"
#define ERR_USERNOTINCHANNEL(Nick, Channel) "ircserv " + Nick + " " + Channel + " :They aren't on that channel. (441)"
#define ERR_NOTONCHANNEL(Channel) "ircserv " + Channel + " :You're not on that channel. (442)"
#define ERR_USERONCHANNEL(Nick, Channel) "ircserv " + Nick + " " + Channel + " :is already on channel. (443)"
#define ERR_NOTREGISTERED() "ircserv :You have not registered. (451)"
#define ERR_NEEDMOREPARAMS(Command) "ircserv " + Command + " :Not enough parameters. (461)"
#define ERR_ALREADYREGISTERED() "ircserv :You may not reregister. (462)"
#define ERR_PASSWDMISMATCH() "ircserv :Password incorrect. (464)"
#define ERR_YOUREBANNEDCREEP() "ircserv :You banned from this server. (465)"
#define ERR_CHANNELISFULL(Channel) "ircserv " + Channel + " :Cannot join channel. (471)"
#define ERR_UNKNOWNMODE(Modechar) "ircserv " + Modechar + ":is unknown mode char to me. (472)"
#define ERR_INVITEONLYCHAN(Channel) "ircserv " + Channel + " :Cannot join channel. (473)"
#define ERR_BANNEDFROMCHAN(Channel) "ircserv " + Channel + " :Cannot join channel. (474)"
#define ERR_BADCHANNELKEY(Channel) "ircserv " + Channel + " :Cannot join channel. (475)"
#define ERR_NOPRIVILEGES() "ircserv :Permission Denied- You're not an IRC operator. (481)"
#define ERR_CHANOPRIVSNEEDED(Channel) "ircserv " + Channel + " :You're not channel operator. (482)"
#define ERR_INVALIDKEY(Channel) "ircserv " + Channel + " :Key is not well-formed. (525)"